# Generated by Django 4.2 on 2023-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
