# Generated by Django 4.2 on 2023-04-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_postcomment_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
