# Generated by Django 4.2 on 2023-04-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
